import 'package:flutter/material.dart';
import 'package:rick_and_morty/themes/theme_overlays.dart';

class AppThemeData {
  static ThemeData get lightTheme =>
      ThemeData.light(useMaterial3: true).copyWith(
        extensions: <ThemeExtension<CustomThemeOverlay>>{
          CustomThemeOverlay(
            colorError: const Color(0xffEB5757),
            color0B1E2D: const Color(0xff0B61A4),
            colorGreen: const Color(0xff43D049),
            color152A3A: const Color(0xffD2E4FF),
            color5B6975: const Color(0xff001C37),
            colorFFFFFF: const Color(0xffEADDFF),
            color6E798C: const Color(0xff21005D),
            color22A2BD: const Color(0xffD0BCFF),
            // colorBottomNavBar: const Color(0xff22A2BD),
            // colorOnPrimaryFixedVariant: const Color(0xff4F378B),
            // colorSecondary: const Color(0xff2E5DA8),
            // colorOnSecondary: const Color(0xffFFFFFF),
            // colorSecondaryContainer: const Color(0xffD7E2FF),
            // colorOnSecondaryContainer: const Color(0xff001A40),
            // colorSecondaryFixed: const Color(0xffE8DEF8),
            // colorOnSecondaryFixed: const Color(0xff1D192B),
            // colorSecondaryFixedDim: const Color(0xffCCC2DC),
            // colorOnSecondaryFixedVariant: const Color(0xff4A4458),
            // colorTertiary: const Color(0xff0B61A4),
            // colorOnTertiary: const Color(0xffFFFFFF),
            // colorTertiaryContainer: const Color(0xffD2E4FF),
            // colorOnTertiaryContainer: const Color(0xff001C37),
            // colorError: const Color(0xffB3261E),
            // colorOnError: const Color(0xffFFFFFF),
            // colorErrorContainer: const Color(0xffF9DEDC),
            // colorOnErrorContainer: const Color(0xff410E0B),
            // colorOutline: const Color(0xff79747E),
            // colorOnBackground: const Color(0xff191C20),
            // colorSurface: const Color(0xffF8F9FF),
            // colorSurfaceVariant: const Color(0xffDFE2EB),
            // colorOnSurface: const Color(0xff191C20),
            // colorOnSurfaceVariant: const Color(0xff43474E),
            // colorSurfaceInverse: const Color(0xff322F35),
            // colorOnSurfaceInverse: const Color(0xffF5EFF7),
            // colorPrimaryInverse: const Color(0xffA0C9FF),
            // colorOutlineVariant: const Color(0xffCAC4D0),
            // colorSurfaceContainerHighest: const Color(0xffD7E4F2),
            // colorSurfaceContainerHigh: const Color(0xffDEE9F5),
            // colorSurfaceContainer: const Color(0xffE6EDF8),
            // colorSurfaceContainerLow: const Color(0xffECF1FA),
            // colorSurfaceContainerLowest: const Color(0xffFFFFFF),
            // colorSurfaceBright: const Color(0xffF8F9FF),
            // colorSurfaceDim: const Color(0xffD8DCE1),
          ),
        },
      );

  static ThemeData get darkTheme => ThemeData.dark(useMaterial3: true).copyWith(
        extensions: <ThemeExtension<CustomThemeOverlay>>{
          CustomThemeOverlay(
            colorError: const Color(0xffEB5757),
            color0B1E2D: const Color(0xff0B1E2D),
            colorGreen: const Color(0xff43D049),
            color152A3A: const Color(0xff152A3A),
            color5B6975: const Color(0xff5B6975),
            colorFFFFFF: const Color(0xffFFFFFF),
            color6E798C: const Color(0xff6E798C),
            color22A2BD: const Color(0xff22A2BD),
            // colorBottomNavBar: const Color(0xff43D049),
            // colorOnPrimaryFixedVariant: const Color(0xff4F378B),
            // colorSecondary: const Color(0xffACC7FF),
            // colorOnSecondary: const Color(0xff002F67),
            // colorSecondaryContainer: const Color(0xff08458E),
            // colorOnSecondaryContainer: const Color(0xffD7E2FF),
            // colorSecondaryFixed: const Color(0xffE8DEF8),
            // colorOnSecondaryFixed: const Color(0xff1D192B),
            // colorSecondaryFixedDim: const Color(0xffCCC2DC),
            // colorOnSecondaryFixedVariant: const Color(0xff4A4458),
            // colorTertiary: const Color(0xffA0C9FF),
            // colorOnTertiary: const Color(0xff00325A),
            // colorTertiaryContainer: const Color(0xff00497F),
            // colorOnTertiaryContainer: const Color(0xffD2E4FF),
            // colorError: const Color(0xffF2B8B5),
            // colorOnError: const Color(0xff601410),
            // colorErrorContainer: const Color(0xff8C1D18),
            // colorOnErrorContainer: const Color(0xffF9DEDC),
            // colorOutline: const Color(0xff938F99),
            // colorOnBackground: const Color(0xffDBDDE3),
            // colorSurface: const Color(0xff191C20),
            // colorSurfaceVariant: const Color(0xff43474E),
            // colorOnSurface: const Color(0xffDBDDE3),
            // colorOnSurfaceVariant: const Color(0xffC3C6CF),
            // colorSurfaceInverse: const Color(0xffE6E0E9),
            // colorOnSurfaceInverse: const Color(0xff322F35),
            // colorPrimaryInverse: const Color(0xff0B61A4),
            // colorOutlineVariant: const Color(0xff49454F),
            // colorSurfaceContainerHighest: const Color(0xff36404C),
            // colorSurfaceContainerHigh: const Color(0xff282F38),
            // colorSurfaceContainer: const Color(0xff242A31),
            // colorSurfaceContainerLow: const Color(0xff20252B),
            // colorSurfaceContainerLowest: const Color(0xff0F0D13),
            // colorSurfaceBright: const Color(0xff282F38),
            // colorSurfaceDim: const Color(0xff20252B),
          ),
        },
      );
}
